# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161021_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='files',
        ),
    ]
