# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_person_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Femame')], default='Male', max_length=20),
        ),
    ]
