# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-24 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161021_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='amount_left',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='amount_paid',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='note',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.CharField(default=9, max_length=26),
        ),
    ]
