# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161029_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.FileField(null=True, upload_to=b''),
        ),
    ]
