# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-29 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161029_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
