# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-30 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20161029_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
